<a href="https://colab.research.google.com/github/fengivan/382L-HW5/blob/master/HW5Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.set_printoptions(linewidth=np.inf)


In [ ]:
#creating the test matrix

I=np.identity(5)
B=np.matrix([[-8,2,0,0,0],[1,-8,1,0,0],[0,1,-8,1,0],[0,0,1,-8,1],[0,0,0,1,-8]])
Z=np.zeros((5,5))

#vector of constants
b=np.full((25,1), -1) 

matrix=np.concatenate((np.subtract(B, 1.5*I), 6*I,Z,Z,Z), axis=1)
matrix=np.concatenate((matrix,np.concatenate((3*I, B, 3*I, Z,Z), axis=1)),axis=0)
matrix=np.concatenate((matrix,np.concatenate((Z,3*I,B,3*I,Z),axis=1)),axis=0)
matrix=np.concatenate((matrix,np.concatenate((Z,Z,3*I,B,3*I,),axis=1)),axis=0)
matrix=np.concatenate((matrix,np.concatenate((Z,Z,Z,6*I,B),axis=1)),axis=0)

print("matrix:")
print(matrix)
print("b:")
print(b)

In [ ]:
#Because the main diagonal of this matrix is the largest element, no pivoting is needed
#if pivoting is needed, PAx=b,  
#matrix(row,column)


def LU(A):                        #this function returns L and U, where A=LU
  A = A.astype(float)
  L=np.identity(len(A))

  for i in range(0,len(A)):       #iterate through diagonal elements, starting at row/column 0
    for j in range(i+1, len(A)):  #iterate through rows below i
      if A[j,i]!=0:               #if the row does not have a leading 0, make it 0
        ratio=-A[j,i]/A[i,i]      #figure out what fraction of the ith row you need to add to the jth row so that the jth row will have a leading 0
        L[j,i]=-ratio             #keep track what you multiplied by in the L matrix
        A[j]=A[j]+A[i]*ratio      #the jth row becomes the jth row plus (ith row* ratio). The jth row now has a leading 0
 
  return L, A                     #at the end of this process, L is a lower triangular matrix, and A has been changed to an upper triangular matrix.

def solve(A, b):                  #this function returns x, if Ax=b. This is assuming that no pivoting is needed for A
  L, U=LU(A)                      #get L and U
  Ux=np.zeros(len(A))             #Ax=b -> LUx=b, solve L(Ux)=b for Ux first 
  for i in range(0,len(A)):       #iterate from 0 to len(A)
    Ux[i]=b[i]                    #set Ux at i to b at i
    for j in range(0, i):         #subtract the previous terms of Ux multipled by the L coefficients
      Ux[i]-=L[i,j]*Ux[j]
  
  x=np.zeros(len(A))
  for i in reversed(range(0, len(A))):  #Solve for x given Ux and U
    for j in range(i, len(A)):          #iterate through all the higher terms of x
      x[i]+=U[i,j]*x[j]                 #sum up the U coefficients * the higher terms of x
    x[i]=(Ux[i]-x[i])/U[i, i]           #the ith x is equal to (Ux[i] minus the sum) divided by the leading coefficient
  
  return  np.atleast_2d(x).T            #return a column vector with the solution





In [ ]:

mysolu= solve(matrix,b)                                 #call my solve function with matrix and b
actualsolu = np.linalg.solve(matrix, b)                 #call built in linalg function
print(" My solution,    Actual solution,  difference")
print(np.concatenate((mysolu, actualsolu, abs(mysolu-actualsolu)),axis=1))# compare the two solutions

 My solution,    Actual solution,  difference
[[3.72851307e+00 3.72851307e+00 2.22044605e-15]
 [3.61678469e+00 3.61678469e+00 1.33226763e-15]
 [3.26570222e+00 3.26570222e+00 8.88178420e-16]
 [2.62454228e+00 2.62454228e+00 4.44089210e-16]
 [1.59608112e+00 1.59608112e+00 0.00000000e+00]
 [4.53121747e+00 4.53121747e+00 2.66453526e-15]
 [4.39420655e+00 4.39420655e+00 1.77635684e-15]
 [3.96380736e+00 3.96380736e+00 8.88178420e-16]
 [3.17856138e+00 3.17856138e+00 0.00000000e+00]
 [1.92303806e+00 1.92303806e+00 0.00000000e+00]
 [5.09192914e+00 5.09192914e+00 3.55271368e-15]
 [4.93609116e+00 4.93609116e+00 4.44089210e-15]
 [4.44686142e+00 4.44686142e+00 1.77635684e-15]
 [3.55600627e+00 3.55600627e+00 0.00000000e+00]
 [2.13916659e+00 2.13916659e+00 4.44089210e-16]
 [5.42319947e+00 5.42319947e+00 2.66453526e-15]
 [5.25577302e+00 5.25577302e+00 3.55271368e-15]
 [4.73045728e+00 4.73045728e+00 8.88178420e-16]
 [3.77544601e+00 3.77544601e+00 4.44089210e-16]
 [2.26273741e+00 2.26273741e+00 0.00000000